name: yolo
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.4
  - torchvision
  - pytorch-cuda=12.4
  - pip
  - pip:
      - ultralytics
      - onnx
      - onnxruntime-gpu
      - opencv-python>=5.0
      - labelImg
